import {
  LiveStream,
  SocialPost,
  Visitor,
  DailyTask,
  RewardItem,
  BackpackItem,
  LeaderboardUser,
} from "./types";

// Multilingual Dictionaries for professional localization
export type Language = "en" | "am" | "om" | "ar" | "zh" | "tl";

export const LANGUAGES: { code: Language; name: string }[] = [
  { code: "en", name: "English" },
  { code: "am", name: "አማርኛ (Amharic)" },
  { code: "om", name: "Afaan Oromoo" },
  { code: "ar", name: "العربية (Arabic)" },
  { code: "zh", name: "中文 (Chinese)" },
  { code: "tl", name: "Tagalog" },
];

export const DICTIONARY: Record<Language, Record<string, string>> = {
  en: {
    appName: "Spark",
    tagline: "Live-streaming & Social Platform for Diverse Culture & Tourism",
    aboutMe: "About Me",
    projects: "Projects",
    aiExpertise: "AI Expertise",
    testimonials: "Testimonials",
    enterApp: "Launch Spark Platform",
    signIn: "Sign In",
    signUp: "Sign Up",
    signOut: "Sign Out",
    welcome: "Welcome",
    email: "Email address",
    password: "Password",
    faceIdRequired: "Security Compliance: Face ID Verification Required",
    faceIdRegister: "Please register your biometrics (Face ID) to qualify for tasks, bonuses, and security compliance.",
    faceIdSuccess: "Face registration complete. Verifying every 30 days.",
    faceIdVerifyBtn: "Scan Face ID Now",
    backpack: "Backpack & Inventory",
    leaderboard: "Top Contributors",
    payoutConfig: "Payout Configuration",
    payoutDescription: "Select your region and link your local or international payment methods.",
    honorCenter: "Honor & Activity Center",
    helpSection: "Help & Technical Support",
    privacySettings: "Privacy & Controls",
    visibilityToggles: "Personal Visibility Settings",
    visitors: "Recent Visitors",
    liveStreams: "Cultural Live Streams",
    trendingPost: "Trending Posts & Feeds",
    searchPlaceholder: "Search users by name or App ID...",
    dailyTasksProgress: "Daily Rewards & Progress",
  },
  am: {
    appName: "ስፓርክ (Spark)",
    tagline: "ለባህልና ቱሪዝም የቀጥታ ስርጭት እና ማህበራዊ አውታረ መረብ",
    aboutMe: "ስለ እኔ",
    projects: "ፕሮጀክቶች",
    aiExpertise: "የአርቴፊሻል ኢንተለጀንስ ልምድ",
    testimonials: "ምስክርነቶች",
    enterApp: "የስፓርክ መድረክን ክፈት",
    signIn: "ግባ",
    signUp: "ተመዝገብ",
    signOut: "ውጣ",
    welcome: "እንኳን ደህና መጡ",
    email: "ኢሜይል አድራሻ",
    password: "የይለፍ ቃል",
    faceIdRequired: "የደህንነት ማረጋገጫ፡ የፊት መታወቂያ (Face ID) ያስፈልጋል",
    faceIdRegister: "ለዕለታዊ ተግባራት፣ ለጉርሻዎች እና ለደህንነት ደንቦች የእርስዎን ባዮሜትሪክስ (Face ID) ያስመዝግቡ።",
    faceIdSuccess: "የፊት ምዝገባ ተጠናቋል። በየ30 ቀኑ ይረጋገጣል።",
    faceIdVerifyBtn: "ፊትን አሁን አንብብ",
    backpack: "የጀርባ ቦርሳ እና ሽልማቶች",
    leaderboard: "ከፍተኛ አስተዋጽዖ አበርካቾች",
    payoutConfig: "የክፍያ ማዋቀሪያ",
    payoutDescription: "ክልልዎን ይምረጡ እና የአገር ውስጥ ወይም ዓለም አቀፍ የክፍያ መንገዶችን ያገናኙ።",
    honorCenter: "የክብር እና የዕለታዊ ተግባር ማዕከል",
    helpSection: "የእርዳታ እና የቴክኒክ ድጋፍ",
    privacySettings: "የግል ደህንነት እና መቆጣጠሪያዎች",
    visibilityToggles: "የግል ታይነት ቅንብሮች",
    visitors: "የቅርብ ጊዜ ጎብኚዎች",
    liveStreams: "የቀጥታ የባህል ስርጭቶች",
    trendingPost: "ታዋቂ ልጥፎች እና ምግቦች",
    searchPlaceholder: "ተጠቃሚዎችን በስም ወይም በApp ID ፈልግ...",
    dailyTasksProgress: "ዕለታዊ ሽልማቶች እና ሂደቶች",
  },
  om: {
    appName: "Spark",
    tagline: "Agarsiisa Kallattii fi Hawaasummaa Aadaa fi Turiizimiif",
    aboutMe: "Waa'ee Koo",
    projects: "Pirojektoota",
    aiExpertise: "Ogummaa AI",
    testimonials: "Ragaalee",
    enterApp: "Banri Spark Mandara",
    signIn: "Seeni",
    signUp: "Galmaa'i",
    signOut: "Bahi",
    welcome: "Akkam Jirtu",
    email: "Teessoo Imeelii",
    password: "Jecha Icchitii",
    faceIdRequired: "Mirkaneessa Nageenyaa: Face ID barbaachisaadha",
    faceIdRegister: "Giddugala hojii fi bonasii gochuuf Face ID galmeessi.",
    faceIdSuccess: "Galmeen Face ID milkaa'eera. Guyyaa 30 keessatti mirkanaa'a.",
    faceIdVerifyBtn: "Amma Face ID Scan Godhi",
    backpack: "Kofoo fi Badhaasota",
    leaderboard: "Gumaachitoota Ol'aanoo",
    payoutConfig: "Qophii Kaffaltii",
    payoutDescription: "Naannoo kee filadhu kaffaltii biyya keessaa fi biyya alaa hidhadhu.",
    honorCenter: "Giddugala Kabajaa fi Raawwii",
    helpSection: "Gargaarsa fi Deeggarsa",
    privacySettings: "Icitii fi To'annoo",
    visibilityToggles: "Qophii Mul'achuu Dhuunfaa",
    visitors: "Imaltoota Dhiyoo",
    liveStreams: "Tamsaasa Kallattii Aadaa",
    trendingPost: "Barruulee Beekamoo",
    searchPlaceholder: "Maqaan ykn App ID barbaadi...",
    dailyTasksProgress: "Badhaasa Guyyaa fi Adeemsa",
  },
  ar: {
    appName: "سبارك (Spark)",
    tagline: "البث المباشر والتواصل الاجتماعي لتعزيز الثقافة والسياحة",
    aboutMe: "نبذة عني",
    projects: "المشاريع",
    aiExpertise: "خبرة في الذكاء الاصطناعي",
    testimonials: "الشهادات",
    enterApp: "إطلاق منصة سبارك",
    signIn: "تسجيل الدخول",
    signUp: "إنشاء حساب",
    signOut: "تسجيل الخروج",
    welcome: "مرحباً بك",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    faceIdRequired: "الامتثال للأمن: مطلوب التحقق من هوية الوجه",
    faceIdRegister: "يرجى تسجيل القياسات الحيوية للوجه للتأهل للمهام اليومية والمكافآت.",
    faceIdSuccess: "اكتمل تسجيل الوجه. يتم التحقق كل 30 يومًا.",
    faceIdVerifyBtn: "مسح هوية الوجه الآن",
    backpack: "حقيبة الظهر والجوائز",
    leaderboard: "المساهمون الأوائل",
    payoutConfig: "إعدادات الدفع",
    payoutDescription: "اختر منطقتك وقم بربط طرق الدفع المحلية أو الدولية الخاصة بك.",
    honorCenter: "مركز الشرف والأنشطة",
    helpSection: "المساعدة والدعم الفني",
    privacySettings: "الخصوصية والتحكم",
    visibilityToggles: "إعدادات الرؤية الشخصية",
    visitors: "الزوار الأخيرون",
    liveStreams: "البث الثقافي المباشر",
    trendingPost: "المنشورات الشائعة",
    searchPlaceholder: "البحث عن المستخدمين بالاسم أو معرف التطبيق...",
    dailyTasksProgress: "المكافآت اليومية والتقدم",
  },
  zh: {
    appName: "星火 (Spark)",
    tagline: "旨在促进多元文化与旅游的直播与社交平台",
    aboutMe: "关于我",
    projects: "核心项目",
    aiExpertise: "AI专业技能",
    testimonials: "客户评价",
    enterApp: "启动 Spark 平台",
    signIn: "登录",
    signUp: "注册",
    signOut: "登出",
    welcome: "欢迎回来",
    email: "电子邮箱",
    password: "登录密码",
    faceIdRequired: "安全合规：需要进行人脸识别验证",
    faceIdRegister: "请注册您的生物特征（Face ID）以获取参与每日任务的资格和红利。",
    faceIdSuccess: "人脸识别注册成功。每30天进行一次周期验证。",
    faceIdVerifyBtn: "立即扫描面容",
    backpack: "背包与收藏徽章",
    leaderboard: "贡献贡献排行榜",
    payoutConfig: "提现渠道配置",
    payoutDescription: "选择您的所属区域并绑定对应的本地或国际支付渠道。",
    honorCenter: "荣誉与任务中心",
    helpSection: "帮助与技术支持",
    privacySettings: "隐私及可见性设置",
    visibilityToggles: "个人可见度控制",
    visitors: "访客足迹",
    liveStreams: "多元文化特色直播",
    trendingPost: "热门动态与分享",
    searchPlaceholder: "通过名称或 App ID 搜索用户...",
    dailyTasksProgress: "每日任务奖励进度",
  },
  tl: {
    appName: "Spark",
    tagline: "Live-streaming & Social Platform para sa Kultura at Turismo",
    aboutMe: "Tungkol sa Akin",
    projects: "Mga Proyekto",
    aiExpertise: "Kasanayan sa AI",
    testimonials: "Mga Patotoo",
    enterApp: "Buksan ang Spark",
    signIn: "Mag-sign In",
    signUp: "Mag-sign Up",
    signOut: "Mag-log Out",
    welcome: "Maligayang Pagdating",
    email: "Email address",
    password: "Password",
    faceIdRequired: "Security Compliance: Face ID Verification Kailangan",
    faceIdRegister: "Mangyaring irehistro ang iyong Face ID upang makasali sa mga pang-araw-araw na gawain at bonus.",
    faceIdSuccess: "Kumpleto ang rehistro. Beripikasyon tuwing 30 araw.",
    faceIdVerifyBtn: "I-scan ang Face ID Ngayon",
    backpack: "Backpack at Imbentaryo",
    leaderboard: "Mga Top Contributor",
    payoutConfig: "Pag-configure ng Payout",
    payoutDescription: "Piliin ang iyong rehiyon at i-link ang iyong local o international na payout channels.",
    honorCenter: "Honor & Activity Center",
    helpSection: "Tulong at Suporta",
    privacySettings: "Privacy at Kontrol",
    visibilityToggles: "Mga Setting ng Visibility",
    visitors: "Kamakailang mga Bisita",
    liveStreams: "Araw-araw na Live Stream",
    trendingPost: "Mga Trending na Post",
    searchPlaceholder: "Maghanap ng mga user gamit ang pangalan o App ID...",
    dailyTasksProgress: "Araw-araw na Gampanin at Proseso",
  },
};

// Initial Cultural Streams Promoting Local tourism & diverse heritage
export const INITIAL_STREAMS: LiveStream[] = [
  {
    id: "stream-1",
    streamerName: "Lalibela Tour Guide",
    streamerId: "guide_lalibela",
    streamerAvatar: "https://images.unsplash.com/photo-1542281286-9e0a16bb7366?auto=format&fit=crop&q=80&w=200",
    title: "Exploring the Rock-Hewn Churches of Lalibela 🇪🇹",
    tags: ["#Lalibela", "#Tourism", "#EthiopianCulture", "#Heritage"],
    viewerCount: 1420,
    isLive: true,
    bgGradient: "from-amber-600 via-orange-500 to-yellow-600",
    comments: [
      { id: "c1", userName: "Abebe_K", text: "Incredible historical preservation!", timestamp: "18:42" },
      { id: "c2", userName: "GlobalTraveler", text: "On my bucket list for next year!", timestamp: "18:43" },
      { id: "c3", userName: "Sara_A", text: "Ethiopia is so beautiful ❤️", timestamp: "18:44" },
    ],
  },
  {
    id: "stream-2",
    streamerName: "Coffee Ceremony Master",
    streamerId: "coffee_heritage",
    streamerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200",
    title: "Traditional Ethiopian Coffee Brewing Ceremony ☕",
    tags: ["#EthiopianCoffee", "#Buna", "#Tradition", "#Rituals"],
    viewerCount: 980,
    isLive: true,
    bgGradient: "from-teal-600 via-emerald-500 to-green-600",
    comments: [
      { id: "c4", userName: "Chala_O", text: "I can smell the frankincense through the stream!", timestamp: "18:40" },
      { id: "c5", userName: "Yuki_S", text: "A beautiful three-cup brewing transition.", timestamp: "18:42" },
    ],
  },
  {
    id: "stream-3",
    streamerName: "Axum Obelisk Watch",
    streamerId: "axum_explorer",
    streamerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200",
    title: "Axumite Monuments & Historic Reign Walkthrough 🏛️",
    tags: ["#Axum", "#Archeology", "#History", "#HornOfAfrica"],
    viewerCount: 650,
    isLive: true,
    bgGradient: "from-blue-600 via-indigo-500 to-purple-600",
    comments: [
      { id: "c6", userName: "Fatima_H", text: "The architectural engineering is mind-boggling.", timestamp: "18:41" },
    ],
  },
];

// Initial Social Posts with custom tags
export const INITIAL_POSTS: SocialPost[] = [
  {
    id: "post-1",
    authorName: "Mezgebu Debeli",
    authorId: "mezgebu_debeli_ai",
    authorAvatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=200",
    content: "Excited to introduce 'Spark', the ultimate ad-supported cultural live streaming ecosystem. Together, we promote diverse culture, preserve historic sights, and build secure local communities!",
    tags: ["#SparkPlatform", "#EthioCulture", "#LiveStream", "#AISecurity"],
    likes: 384,
    isLikedByUser: false,
    shares: 42,
    createdAt: "2 hours ago",
    comments: [
      { id: "p1_c1", userName: "Abyssinia_Fan", text: "Excellent design Mezgebu! The interface feels incredibly smooth.", timestamp: "2h ago" },
      { id: "p1_c2", userName: "TechEnthusiast", text: "Integrating CBE and Telebirr natively for local creators is a major win.", timestamp: "1h ago" },
    ],
  },
  {
    id: "post-2",
    authorName: "Sof Omar Hiker",
    authorId: "sof_omar_caves",
    authorAvatar: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&q=80&w=200",
    content: "Just returned from photographing the underground river caves of Sof Omar. The natural limestone carvings are magnificent. Truly one of the world's best-kept tourism secrets!",
    tags: ["#SofOmar", "#ExploreEthiopia", "#Nature", "#CaveHiking"],
    imageUrl: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&q=80&w=600",
    likes: 219,
    isLikedByUser: false,
    shares: 19,
    createdAt: "5 hours ago",
    comments: [],
  },
];

// Mock Visitors list
export const INITIAL_VISITORS: Visitor[] = [
  { id: "v1", name: "Helen Tesfaye", appId: "SPK-49302", avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=100", visitTime: "5 mins ago" },
  { id: "v2", name: "Yared Abera", appId: "SPK-88329", avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=100", visitTime: "12 mins ago" },
  { id: "v3", name: "Sarah Wang", appId: "SPK-29440", avatarUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=100", visitTime: "30 mins ago" },
  { id: "v4", name: "Mohammad Ali", appId: "SPK-71283", avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=100", visitTime: "1 hour ago" },
];

// Tasks & Badges
export const INITIAL_TASKS: DailyTask[] = [
  { id: "t1", title: "Join Cultural Stream", description: "Watch any live stream for at least 2 minutes", rewardCoins: 50, rewardXp: 30, progress: 1, target: 1, completed: true },
  { id: "t2", title: "Send Direct Message", description: "Message any tourist guide or peer user to request travel tips", rewardCoins: 30, rewardXp: 20, progress: 0, target: 1, completed: false },
  { id: "t3", title: "Interact with Hashtags", description: "Like or comment on posts containing #EthioCulture", rewardCoins: 40, rewardXp: 25, progress: 1, target: 3, completed: false },
  { id: "t4", title: "Monthly Face ID Compliance", description: "Renew or complete your biometric profile matching platform criteria", rewardCoins: 100, rewardXp: 100, progress: 0, target: 1, completed: false },
];

export const REWARDS_SHOP: RewardItem[] = [
  { id: "r1", title: "Kebra Nagast Shield Badge", costCoins: 120, type: "badge", imageUrl: "🛡️" },
  { id: "r2", title: "Simien Ibex Mascot", costCoins: 250, type: "item", imageUrl: "🐐" },
  { id: "r3", title: "Lalibela Cross Pendant (Virtual)", costCoins: 180, type: "badge", imageUrl: "✝️" },
  { id: "r4", title: "Traditional Coffee Brewer Token", costCoins: 100, type: "gift", imageUrl: "☕" },
];

// Backpack Contents
export const INITIAL_BACKPACK: BackpackItem[] = [
  { id: "bp1", name: "Amharic Golden Crown Badge", description: "Earned for supporting local writers and cultural streaming history", qty: 1, type: "badge", iconName: "👑", badgeLevel: 2 },
  { id: "bp2", name: "Telebirr Fast-Pass Booster", description: "Increases processing speed of payout transaction confirmation in the region", qty: 2, type: "powerup", iconName: "⚡" },
  { id: "bp3", name: "Coffee Stream Gift - Buna Rose", description: "Send this beautiful coffee flower virtual gift to active streamers on feed", qty: 5, type: "gift", iconName: "🌹" },
];

// Leaderboard Top Contributors
export const INITIAL_LEADERBOARD: LeaderboardUser[] = [
  { id: "l1", rank: 1, name: "Sintayehu Kebede", appId: "SPK-10022", avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=100", score: 8750, level: 24 },
  { id: "l2", rank: 2, name: "Netsanet Shiferaw", appId: "SPK-44021", avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=100", score: 7200, level: 19 },
  { id: "l3", rank: 3, name: "Alex Johnson", appId: "SPK-90038", avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=100", score: 6450, level: 17 },
  { id: "l4", rank: 4, name: "Mezgebu Debeli", appId: "SPK-11111", avatarUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=100", score: 5500, level: 15 },
  { id: "l5", rank: 5, name: "Guang Zhang", appId: "SPK-38102", avatarUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=100", score: 3900, level: 12 },
];
